MAP: Fix build when using --with-messages=tracker
Commit 15b15167fb2dd82e2189cc1955def1818a7bc6a6 broke the build:

plugins/messages.c:324:42: error: unknown type name ‘messages_update_inbox_cb’
plugins/messages.c:331:5: error: unknown type name ‘messages_set_read_cb’
plugins/messages.c:337:6: error: unknown type name ‘messages_set_delete_cb’