build: BlueZ version 4.100 or later is required
If we use the BlueZ version less than 4.100, then the following
compilation error happens.

Error:
======
btio/btio.c: In function ‘l2cap_connect’:
btio/btio.c:301:6: error: ‘struct sockaddr_l2’ has no member named
 ‘l2_bdaddr_type’
btio/btio.c: In function ‘parse_set_opts’:
btio/btio.c:707:19: error: ‘BDADDR_BREDR’ undeclared (first use in
 this function)
btio/btio.c:707:19: note: each undeclared identifier is reported only
 once for each function it appears in
make[1]: *** [btio/btio.o] Error 1
make: *** [all] Error 2